[package]
name = "aoc25"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.14", features = ["all_default_solvers"] }

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "day10"
harness = false
